# 基础镜像
FROM nginx
# author
MAINTAINER gourddoll

# 挂载目录
VOLUME /home/gourddoll/projects/gourddoll-ui
# 创建目录
RUN mkdir -p /home/gourddoll/projects/gourddoll-ui
# 指定路径
WORKDIR /home/gourddoll/projects/gourddoll-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/gourddoll/projects/gourddoll-ui
