/*
 Navicat Premium Data Transfer

 Source Server         : aliyun
 Source Server Type    : MySQL
 Source Server Version : 50730
 Source Host           : 39.99.195.107:13306
 Source Schema         : gd-config

 Target Server Type    : MySQL
 Target Server Version : 50730
 File Encoding         : 65001

 Date: 19/12/2020 23:04:06
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 53 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (1, 'application-dev.yml', 'DEFAULT_GROUP', 'spring:\n  main:\n    allow-bean-definition-overriding: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n', '57470c6d167154919418fa150863b7fb', '2019-11-29 16:31:20', '2020-09-01 09:14:30', NULL, '0:0:0:0:0:0:0:1', '', '', '通用配置', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (2, 'gourddoll-gateway-dev.yml', 'DEFAULT_GROUP', 'spring:\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  cloud:\n    gateway:\n      globalcors:\n        cors-configurations:\n        \'[/**]\':\n          #这里有个allowCredentials: true这个东西是设置允许访问携带cookie的，这点一定要和前端对应！\n          allowCredentials: true\n          #可以填写多个域名用\",\"隔开 例如：\"http://www.xiaolc.cn,https://spring.io\"  \"*\"代表允许所有\n          allowedOrigins: \"*\"\n          allowedMethods: \"*\"\n          allowedHeaders: \"*\"\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: gourddoll-auth\n          uri: lb://gourddoll-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: gourddoll-gen\n          uri: lb://gourddoll-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: gourddoll-job\n          uri: lb://gourddoll-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: gourddoll-system\n          uri: lb://gourddoll-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 博客模块\n        - id: gourddoll-blog\n          uri: lb://gourddoll-blog\n          #为访问url添加前缀\n          predicates:\n            - Path=/blog/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', 'af6cb63aa8eb511090a6d7a9923c8dd7', '2020-05-14 14:17:55', '2020-12-12 17:07:00', NULL, '103.116.47.207', '', '', '网关模块', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (3, 'gourddoll-auth-dev.yml', 'DEFAULT_GROUP', 'spring: \n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n', '4fa761f4340accff172dc36f478fff3c', '2020-05-14 13:20:49', '2020-12-19 22:30:00', NULL, '103.116.47.212', '', '', '认证中心', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (4, 'gourddoll-monitor-dev.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  security:\n    user:\n      name: gourddoll\n      password: 123456\n  boot:\n    admin:\n      ui:\n        title: 葫芦娃服务状态监控\n', '2630eb31a4c6079d2417f5b28eea8c55', '2020-05-19 15:14:01', '2020-11-15 14:54:18', NULL, '0:0:0:0:0:0:0:1', '', '', '监控中心', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (5, 'gourddoll-system-dev.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://127.0.0.1:8080/auth/oauth/token', '0abe683ef68a60b42b7afbee7bbb52aa', '2020-05-14 13:37:04', '2020-12-19 22:30:50', NULL, '103.116.47.212', '', '', '系统模块', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (6, 'gourddoll-gen-dev.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource: \n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://127.0.0.1:8080/auth/oauth/token\n\n# 代码生成\ngen: \n  # 作者\n  author: gourddoll\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.gourddoll.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', 'e24c369ef63659a7fa2cf06cbb9f9d3d', '2020-05-14 13:54:50', '2020-12-19 22:31:33', NULL, '103.116.47.212', '', '', '代码生成', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (7, 'gourddoll-job-dev.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.job.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 定时任务接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://127.0.0.1:8080/auth/oauth/token\n', '68079dc4abcee02c610158ba9ed32a69', '2020-05-14 13:58:46', '2020-12-19 22:31:58', NULL, '103.116.47.212', '', '', '定时任务', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (8, 'sentinel-gourddoll-gateway', 'DEFAULT_GROUP', '[\n    {\n        \"resource\": \"gourddoll-auth\",\n        \"count\": 500,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"gourddoll-system\",\n        \"count\": 1000,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"gourddoll-gen\",\n        \"count\": 200,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"gourddoll-job\",\n        \"count\": 300,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n    {\n        \"resource\": \"gourddoll-blog\",\n        \"count\": 300,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    }\n]', 'b28d0c5b2ef13dc2c51e7707506ac384', '2020-06-09 12:14:01', '2020-12-19 22:32:45', NULL, '103.116.47.212', '', '', 'null', 'null', 'null', 'json', 'null');
INSERT INTO `config_info` VALUES (10, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 博客模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://127.0.0.1:8080/auth/oauth/token', 'f24569e4c5bde239ff2fbd67106c9153', '2020-11-28 16:40:57', '2020-12-19 22:33:57', NULL, '103.116.47.212', '', '', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (13, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://127.0.0.1:8080/auth/oauth/token', 'a50b9e9c88c48cecd85c4a3c4e36780a', '2020-11-29 18:04:41', '2020-12-19 22:34:38', NULL, '103.116.47.212', '', '', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (33, 'application-prod.yml', 'DEFAULT_GROUP', 'spring:\n  main:\n    allow-bean-definition-overriding: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n', '57470c6d167154919418fa150863b7fb', '2020-12-19 22:24:15', '2020-12-19 22:24:15', NULL, '103.116.47.212', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (34, 'gourddoll-gateway-prod.yml', 'DEFAULT_GROUP', 'spring:\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  cloud:\n    gateway:\n      globalcors:\n        cors-configurations:\n        \'[/**]\':\n          #这里有个allowCredentials: true这个东西是设置允许访问携带cookie的，这点一定要和前端对应！\n          allowCredentials: true\n          #可以填写多个域名用\",\"隔开 例如：\"http://www.xiaolc.cn,https://spring.io\"  \"*\"代表允许所有\n          allowedOrigins: \"*\"\n          allowedMethods: \"*\"\n          allowedHeaders: \"*\"\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: gourddoll-auth\n          uri: lb://gourddoll-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: gourddoll-gen\n          uri: lb://gourddoll-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: gourddoll-job\n          uri: lb://gourddoll-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: gourddoll-system\n          uri: lb://gourddoll-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 博客模块\n        - id: gourddoll-blog\n          uri: lb://gourddoll-blog\n          #为访问url添加前缀\n          predicates:\n            - Path=/blog/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', 'af6cb63aa8eb511090a6d7a9923c8dd7', '2020-12-19 22:25:08', '2020-12-19 22:25:08', NULL, '103.116.47.212', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (35, 'gourddoll-auth-prod.yml', 'DEFAULT_GROUP', 'spring: \n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n', 'aad55fe05395e40f1f161993006a3ae2', '2020-12-19 22:26:10', '2020-12-19 22:35:57', NULL, '103.116.47.212', '', '', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (36, 'gourddoll-monitor-prod.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  security:\n    user:\n      name: gourddoll\n      password: 123456\n  boot:\n    admin:\n      ui:\n        title: 葫芦娃服务状态监控\n', '2630eb31a4c6079d2417f5b28eea8c55', '2020-12-19 22:26:23', '2020-12-19 22:26:23', NULL, '103.116.47.212', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (37, 'gourddoll-system-prod.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'cfd9459b633860d73a4f1ad962888820', '2020-12-19 22:27:32', '2020-12-19 22:27:32', NULL, '103.116.47.212', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (38, 'gourddoll-gen-prod.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource: \n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token\n\n# 代码生成\ngen: \n  # 作者\n  author: gourddoll\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.gourddoll.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', 'bb2b850b636402f6d1864fe23308c6ec', '2020-12-19 22:27:32', '2020-12-19 22:36:56', NULL, '103.116.47.212', '', '', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (39, 'gourddoll-job-prod.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.job.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 定时任务接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token\n', '5d905bf715cf274681226269f6f7ec12', '2020-12-19 22:27:32', '2020-12-19 22:37:41', NULL, '103.116.47.212', '', '', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (41, 'gourddoll-blog-prod.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 博客模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'fcb1c86ff68727cb6d7b0b7fdc41995c', '2020-12-19 22:28:11', '2020-12-19 22:28:11', NULL, '103.116.47.212', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (42, 'gourddoll-search-prod.yml', 'DEFAULT_GROUP', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'e31f15e5e67e062c85baa73143d4ad74', '2020-12-19 22:28:11', '2020-12-19 22:28:11', NULL, '103.116.47.212', '', '', NULL, NULL, NULL, 'yaml', NULL);

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime(0) NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint(64) UNSIGNED NOT NULL,
  `nid` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 62 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (6, 17, 'gourddoll-gen-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource: \n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.vip\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token\n\n# 代码生成\ngen: \n  # 作者\n  author: gourddoll\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.gourddoll.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', '046ce2658433a5317bd01be60ef27c1a', '2020-11-28 15:32:43', '2020-11-28 15:32:43', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 18, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.vip\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', '1d385307293b4932c54e01158dbe1ed4', '2020-11-28 16:40:56', '2020-11-28 16:40:57', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (10, 19, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.vip\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', '1d385307293b4932c54e01158dbe1ed4', '2020-11-28 16:41:28', '2020-11-28 16:41:28', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (5, 20, 'gourddoll-system-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.vip\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', '1d385307293b4932c54e01158dbe1ed4', '2020-11-28 16:41:48', '2020-11-28 16:41:48', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (7, 21, 'gourddoll-job-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.job.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 定时任务接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.vip\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token\n', 'c3813869a011b02dbc6c00673acb91fe', '2020-11-29 12:04:29', '2020-11-29 12:04:29', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (2, 22, 'gourddoll-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: gourddoll-auth\n          uri: lb://gourddoll-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: gourddoll-gen\n          uri: lb://gourddoll-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: gourddoll-job\n          uri: lb://gourddoll-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: gourddoll-system\n          uri: lb://gourddoll-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', '91c9331daf72fab2e1488efee92823de', '2020-11-29 13:40:55', '2020-11-29 13:40:56', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 23, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'c9aabcd87bc90c157e6e01c883848fd5', '2020-11-29 18:04:40', '2020-11-29 18:04:41', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (13, 24, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'c9aabcd87bc90c157e6e01c883848fd5', '2020-11-29 18:09:47', '2020-11-29 18:09:47', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 25, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '', 'server:\n  port: 9205\n  tomcat:\n    uri-encoding: utf-8\n  servlet:\n    context-path: /@project.artifactId@\n# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', '2385e5aedd86d814daa1475c2d0c6268', '2020-11-29 18:10:24', '2020-11-29 18:10:25', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (10, 26, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'c9aabcd87bc90c157e6e01c883848fd5', '2020-12-02 13:03:49', '2020-12-02 21:03:49', NULL, '182.150.122.101', 'U', '');
INSERT INTO `his_config_info` VALUES (5, 27, 'gourddoll-system-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'c9aabcd87bc90c157e6e01c883848fd5', '2020-12-02 13:04:12', '2020-12-02 21:04:13', NULL, '182.150.122.101', 'U', '');
INSERT INTO `his_config_info` VALUES (10, 28, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'e4b5e6d6898065f82f8f1ab2fa4c135d', '2020-12-02 13:04:43', '2020-12-02 21:04:43', NULL, '182.150.122.101', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 29, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', '0a6e52b07e6d95c1fad104c06b424e71', '2020-12-03 14:23:56', '2020-12-03 22:23:57', NULL, '103.116.47.59', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 30, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', '9b3d2848a04c1c9794a005d4d1b6e863', '2020-12-03 14:24:29', '2020-12-03 22:24:30', NULL, '103.116.47.59', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 31, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', '8f00015640072d5b999c5b8ddbb99649', '2020-12-03 15:00:46', '2020-12-03 23:00:47', NULL, '103.116.47.59', 'U', '');
INSERT INTO `his_config_info` VALUES (3, 32, 'gourddoll-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n', '9dea93af936fca974b8e6d147567f738', '2020-12-05 08:45:23', '2020-12-05 16:45:23', NULL, '103.116.47.49', 'U', '');
INSERT INTO `his_config_info` VALUES (5, 33, 'gourddoll-system-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'f44537eba396db5909fd019c77a18232', '2020-12-05 08:45:42', '2020-12-05 16:45:42', NULL, '103.116.47.49', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 34, 'gourddoll-gen-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource: \n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token\n\n# 代码生成\ngen: \n  # 作者\n  author: gourddoll\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.gourddoll.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', '7c1de3cde0181f2611dc756e6c74b1d7', '2020-12-05 08:46:21', '2020-12-05 16:46:21', NULL, '103.116.47.49', 'U', '');
INSERT INTO `his_config_info` VALUES (10, 35, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'f44537eba396db5909fd019c77a18232', '2020-12-05 08:46:35', '2020-12-05 16:46:35', NULL, '103.116.47.49', 'U', '');
INSERT INTO `his_config_info` VALUES (10, 36, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'e4b5e6d6898065f82f8f1ab2fa4c135d', '2020-12-05 09:26:58', '2020-12-05 17:26:59', NULL, '182.150.122.101', 'U', '');
INSERT INTO `his_config_info` VALUES (5, 37, 'gourddoll-system-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'e4b5e6d6898065f82f8f1ab2fa4c135d', '2020-12-08 15:29:06', '2020-12-08 23:29:06', NULL, '103.116.47.207', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 38, 'gourddoll-gen-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource: \n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token\n\n# 代码生成\ngen: \n  # 作者\n  author: gourddoll\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.gourddoll.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', '7bdceb8af520c8ae94a87f6c4047e1fd', '2020-12-08 15:30:00', '2020-12-08 23:30:00', NULL, '103.116.47.207', 'U', '');
INSERT INTO `his_config_info` VALUES (10, 39, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', 'b58318e2d6c4a4d2572fc0d58ee2f42b', '2020-12-08 15:30:34', '2020-12-08 23:30:35', NULL, '103.116.47.207', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 40, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token', '076faf2f5f7ebe0b78e2fced4f38f100', '2020-12-08 15:30:50', '2020-12-08 23:30:50', NULL, '103.116.47.207', 'U', '');
INSERT INTO `his_config_info` VALUES (2, 41, 'gourddoll-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: gourddoll-auth\n          uri: lb://gourddoll-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: gourddoll-gen\n          uri: lb://gourddoll-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: gourddoll-job\n          uri: lb://gourddoll-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: gourddoll-system\n          uri: lb://gourddoll-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 博客模块\n        - id: gourddoll-blog\n          uri: lb://gourddoll-blog\n          #为访问url添加前缀\n          predicates:\n            - Path=/blog/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', 'ef925bc228828e8681aff8f82e42dc53', '2020-12-12 09:07:00', '2020-12-12 17:07:00', NULL, '103.116.47.207', 'U', '');
INSERT INTO `his_config_info` VALUES (10, 42, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'c57d4e689d999f55ba647c627c5b82d3', '2020-12-12 15:04:54', '2020-12-12 23:04:55', NULL, '103.116.47.95', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 43, 'application-prod.yml', 'DEFAULT_GROUP', '', 'spring:\n  main:\n    allow-bean-definition-overriding: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n', '57470c6d167154919418fa150863b7fb', '2020-12-19 14:24:15', '2020-12-19 22:24:15', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 44, 'gourddoll-gateway-prod.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  cloud:\n    gateway:\n      globalcors:\n        cors-configurations:\n        \'[/**]\':\n          #这里有个allowCredentials: true这个东西是设置允许访问携带cookie的，这点一定要和前端对应！\n          allowCredentials: true\n          #可以填写多个域名用\",\"隔开 例如：\"http://www.xiaolc.cn,https://spring.io\"  \"*\"代表允许所有\n          allowedOrigins: \"*\"\n          allowedMethods: \"*\"\n          allowedHeaders: \"*\"\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: gourddoll-auth\n          uri: lb://gourddoll-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: gourddoll-gen\n          uri: lb://gourddoll-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: gourddoll-job\n          uri: lb://gourddoll-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: gourddoll-system\n          uri: lb://gourddoll-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 博客模块\n        - id: gourddoll-blog\n          uri: lb://gourddoll-blog\n          #为访问url添加前缀\n          predicates:\n            - Path=/blog/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', 'af6cb63aa8eb511090a6d7a9923c8dd7', '2020-12-19 14:25:07', '2020-12-19 22:25:08', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 45, 'gourddoll-auth-prod.yml', 'DEFAULT_GROUP', '', 'spring: \n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n', '9151af58d532e6890407d2a1c8a993ab', '2020-12-19 14:26:10', '2020-12-19 22:26:10', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 46, 'gourddoll-monitor-prod.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  security:\n    user:\n      name: gourddoll\n      password: 123456\n  boot:\n    admin:\n      ui:\n        title: 葫芦娃服务状态监控\n', '2630eb31a4c6079d2417f5b28eea8c55', '2020-12-19 14:26:23', '2020-12-19 22:26:23', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 47, 'gourddoll-system-prod.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'cfd9459b633860d73a4f1ad962888820', '2020-12-19 14:27:31', '2020-12-19 22:27:32', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 48, 'gourddoll-gen-prod.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource: \n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token\n\n# 代码生成\ngen: \n  # 作者\n  author: gourddoll\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.gourddoll.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', 'fa928854c4cb01ef494e46aa28a84c0e', '2020-12-19 14:27:31', '2020-12-19 22:27:32', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 49, 'gourddoll-job-prod.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.job.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 定时任务接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token\n', '919529f69d8601a26a58cd1c841dcc22', '2020-12-19 14:27:31', '2020-12-19 22:27:32', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 50, 'gourddoll-blog-prod.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 博客模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'fcb1c86ff68727cb6d7b0b7fdc41995c', '2020-12-19 14:28:10', '2020-12-19 22:28:11', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 51, 'gourddoll-search-prod.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'e31f15e5e67e062c85baa73143d4ad74', '2020-12-19 14:28:10', '2020-12-19 22:28:11', NULL, '103.116.47.212', 'I', '');
INSERT INTO `his_config_info` VALUES (3, 52, 'gourddoll-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n', '9151af58d532e6890407d2a1c8a993ab', '2020-12-19 14:29:59', '2020-12-19 22:30:00', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (5, 53, 'gourddoll-system-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'cfd9459b633860d73a4f1ad962888820', '2020-12-19 14:30:50', '2020-12-19 22:30:50', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 54, 'gourddoll-gen-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource: \n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token\n\n# 代码生成\ngen: \n  # 作者\n  author: gourddoll\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.gourddoll.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', 'fa928854c4cb01ef494e46aa28a84c0e', '2020-12-19 14:31:32', '2020-12-19 22:31:33', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (7, 55, 'gourddoll-job-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.job.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 定时任务接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token\n', '919529f69d8601a26a58cd1c841dcc22', '2020-12-19 14:31:57', '2020-12-19 22:31:58', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 56, 'sentinel-gourddoll-gateway', 'DEFAULT_GROUP', '', '[\n    {\n        \"resource\": \"gourddoll-auth\",\n        \"count\": 500,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"gourddoll-system\",\n        \"count\": 1000,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"gourddoll-gen\",\n        \"count\": 200,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"gourddoll-job\",\n        \"count\": 300,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    }\n]', '3b4178ea29c89cd9e18fd15f79911759', '2020-12-19 14:32:44', '2020-12-19 22:32:45', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (10, 57, 'gourddoll-blog-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 博客模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'fcb1c86ff68727cb6d7b0b7fdc41995c', '2020-12-19 14:33:56', '2020-12-19 22:33:57', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 58, 'gourddoll-search-dev.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  data:\n    elasticsearch:\n      cluster-nodes: 39.99.195.107\n      # 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口，这里9200改为9250\n      cluster-port: 9250\n      username: docker-cluster\n      password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:13306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  main:\n    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册\n\n\n# swagger 配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token', 'e31f15e5e67e062c85baa73143d4ad74', '2020-12-19 14:34:37', '2020-12-19 22:34:38', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (35, 59, 'gourddoll-auth-prod.yml', 'DEFAULT_GROUP', '', 'spring: \n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n', '9151af58d532e6890407d2a1c8a993ab', '2020-12-19 14:35:57', '2020-12-19 22:35:57', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (38, 60, 'gourddoll-gen-prod.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource: \n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://39.99.195.107:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.gen.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://39.99.195.107:8080/auth/oauth/token\n\n# 代码生成\ngen: \n  # 作者\n  author: gourddoll\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.gourddoll.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', 'fa928854c4cb01ef494e46aa28a84c0e', '2020-12-19 14:36:56', '2020-12-19 22:36:56', NULL, '103.116.47.212', 'U', '');
INSERT INTO `his_config_info` VALUES (39, 61, 'gourddoll-job-prod.yml', 'DEFAULT_GROUP', '', '# Spring\nspring: \n  redis:\n    host: 39.99.195.107\n    port: 6379\n    password: 123456\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://localhost:3306/gd-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    username: root\n    password: 123456\n\n# Mybatis配置\nmybatis:\n    # 搜索指定包别名\n    typeAliasesPackage: com.gourddoll.job.domain\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\n    mapperLocations: classpath:mapper/**/*.xml\n\n# swagger 配置\nswagger:\n  title: 定时任务接口文档\n  license: Powered By gourddoll\n  licenseUrl: https://gourddoll.com\n  authorization:\n    name: GourdDoll OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: 客户端授权范围\n    token-url-list:\n      - http://localhost:8080/auth/oauth/token\n', '919529f69d8601a26a58cd1c841dcc22', '2020-12-19 14:37:40', '2020-12-19 22:37:41', NULL, '103.116.47.212', 'U', '');

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions`  (
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `resource` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `action` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  UNIQUE INDEX `uk_role_permission`(`role`, `resource`, `action`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of permissions
-- ----------------------------

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  UNIQUE INDEX `idx_user_role`(`username`, `role`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(20) NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint(20) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

SET FOREIGN_KEY_CHECKS = 1;
